apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    backstage.io/kubernetes-id: foo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: foo
  namespace: test
  labels:
    backstage.io/kubernetes-id: foo
---
apiVersion: v1
kind: Service
metadata:
  name: foo
  namespace: test
  labels:
    app: foo
    backstage.io/kubernetes-id: foo
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: foo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
  namespace: test
  labels:
    backstage.io/kubernetes-id: foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
        backstage.io/kubernetes-id: foo
    spec:
      serviceAccountName: foo
      containers:
      - image: foo:1.0
        imagePullPolicy: Always
        name: foo
        ports:
        - containerPort: 80
